# Generated by Django 3.0.3 on 2020-02-14 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wenfo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url_links',
        ),
        migrations.AddField(
            model_name='urllink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='url_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
