# Generated by Django 3.0.3 on 2021-01-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wenfo_app', '0002_auto_20200214_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
